config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "homes#top"
  get "home/about" => "homes#about"
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "search" => "searches#search"
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.find(params[:book_id])
    @comment = Comment.new(comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id
    @comment.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    comment = @book.comments.find(params[:id])
    comment.destroy
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% book.comments.each do |comment| %>
  <% comment_user = comment.user %>
  <tr>
    <td>
      <%= link_to user_path(comment.user), class: "user_#{comment_user.id}" do %>
        <%= attachment_image_tag comment_user, :profile_image, size: "50x50", fallback: "no_image.png" %><br>
        <%= comment_user.name %>
      <% end %>
    </td>
    <td><%= comment.comment %></td>
    <% if comment_user == current_user %>
      <td><%= link_to 'delete', book_comment_path(comment.book_id, comment.id), method: :delete, class: "btn btn-sm btn-danger", remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数： <%= @book.comments.count %>");
$(".comments").html("<%= j(render 'comments/comment', book: @book) %>");
$("#comment_message").val("");

app/views/comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数： <%= @book.comments.count %>");
$(".comments").html("<%= j(render 'comments/comment', book: @book) %>");
$("#comment_message").val("");