config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "homes#top"
  get "home/about" => "homes#about"
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "search" => "searches#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

# アソシエーション
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォロー関連
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
# メソッド  
  # フォロー関連
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  # 検索関連
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  # ゲストログイン関連
  def self.guest
    # ()内の条件と合致するデータがある場合はそれを返し、ない場合は新規作成
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      # ランダムな文字列を生成するRubyのメソッド
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/users/session_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guest userでログインしました'
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guest userでログインしました'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully"
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.png") %></td>
        <td><%= user.name %></td>
        <td><%= user.followings.count %> follow</td>
        <td><%= user.followers.count %> followers</td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete, class: "btn btn-info rounded-pill" %>
            <% else %>
              <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn btn-success rounded-pill" %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr>
    <%= attachment_image_tag(user, :profile_image, size: "100x100", fallback: "no_image.png") %>
  </tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follow</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>Follower</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class="row">
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete, class: "btn btn-info rounded-pill btn-block" %>
    <% else %>
      <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn btn-success rounded-pill btn-block" %>
    <% end %>
  <% else %>
    <% if !(user.name == "guestuser") %>
      <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New Book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New Book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>